In [ ]:
print('Hi')

Hi


Создайте массив из 10 нулей

In [ ]:
import numpy as np
array = np.zeros(10)
print(array)
print(type(array))


[0. 0. 0. 0. 0. 0. 0. 0. 0. 0.]
<class 'numpy.ndarray'>


Создать массив из 10 единиц

In [ ]:
array=np.ones(10)
print(array)

[1. 1. 1. 1. 1. 1. 1. 1. 1. 1.]


Создать массив из 10 пятерок

In [ ]:
array=np.ones(10)*5
print(array)

[5. 5. 5. 5. 5. 5. 5. 5. 5. 5.]


Создать массив из целых чисел от 10 до 50

In [ ]:
array=np.arange(10,51)
print(array)

[10 11 12 13 14 15 16 17 18 19 20 21 22 23 24 25 26 27 28 29 30 31 32 33
 34 35 36 37 38 39 40 41 42 43 44 45 46 47 48 49 50]


Создать массив из четных чисел от 10 до 50

In [ ]:
array=np.arange(10,51,2)
print(array) 

[10 12 14 16 18 20 22 24 26 28 30 32 34 36 38 40 42 44 46 48 50]


Создать матрицу 3х3 с числами от 0 до 8

In [ ]:
arary_2D = np.arange(9).reshape(3,3)
print(array_2D)

[[0 1 2]
 [3 4 5]
 [6 7 8]]


Создать единичную матрицу 3x3

In [ ]:
array_2D = np.eye(3)
print(array_2D)

[[1. 0. 0.]
 [0. 1. 0.]
 [0. 0. 1.]]


Используйте NumPy для генерации случайного числа от 0 до 1

In [ ]:
rand_num = np.random.normal(0,1,1)
print(rand_num)

[0.40160154]


Используйте NumPy для генерации массива из 25 случайных чисел, взятых из стандартного нормального распределения

In [ ]:
rand_num = np.random.normal(0,1,25)
print(rand_num)

[ 0.2949437  -0.64804453 -0.10415562 -1.81658328  1.15119372 -0.57100546
  0.24141995 -0.80505067 -2.22984503 -0.10385211  0.15870684  0.44390008
 -0.79843959  1.21523367 -0.09944425  1.06425235  0.90726898  1.33577216
  0.02269813  1.40727829 -0.92862203 -0.15726368  1.37202976 -1.27782317
  0.90856136]


Создайте следующую матрицу используя функции библиотеки NumPy:

In [ ]:
import numpy as np
a = np.linspace(0.01, 1, 100).reshape(10,10)
print(a)

[[0.01 0.02 0.03 0.04 0.05 0.06 0.07 0.08 0.09 0.1 ]
 [0.11 0.12 0.13 0.14 0.15 0.16 0.17 0.18 0.19 0.2 ]
 [0.21 0.22 0.23 0.24 0.25 0.26 0.27 0.28 0.29 0.3 ]
 [0.31 0.32 0.33 0.34 0.35 0.36 0.37 0.38 0.39 0.4 ]
 [0.41 0.42 0.43 0.44 0.45 0.46 0.47 0.48 0.49 0.5 ]
 [0.51 0.52 0.53 0.54 0.55 0.56 0.57 0.58 0.59 0.6 ]
 [0.61 0.62 0.63 0.64 0.65 0.66 0.67 0.68 0.69 0.7 ]
 [0.71 0.72 0.73 0.74 0.75 0.76 0.77 0.78 0.79 0.8 ]
 [0.81 0.82 0.83 0.84 0.85 0.86 0.87 0.88 0.89 0.9 ]
 [0.91 0.92 0.93 0.94 0.95 0.96 0.97 0.98 0.99 1.  ]]


Дана стартовая матрица (обязательно запустите код ниже в вашем решении!). 
Эта матрица будет использоваться в последующих задачах

In [ ]:
# это наша стартовая матрица
mat = np.arange(1,26).reshape(5,5)
print(mat)


[[ 1  2  3  4  5]
 [ 6  7  8  9 10]
 [11 12 13 14 15]
 [16 17 18 19 20]
 [21 22 23 24 25]]


Необходимо написать код который вернет следующую матрицу из стартовой

In [ ]:
print(mat[2:,1:])

[[12 13 14 15]
 [17 18 19 20]
 [22 23 24 25]]


Написать код обращения к элементу который вернет значение  20 изстартовой матрицы задачи l

In [42]:
print(mat[3,4])

20


Написать код к стартовой матрице задачи l , который воспроизводит вывод, показанный ниже

In [43]:
print(mat[0:3,1:2])

[[ 2]
 [ 7]
 [12]]


Написать код к стартовой матрице задачи l , который воспроизводит вывод, показанный ниже

In [44]:
print(mat[4:])

[[21 22 23 24 25]]


Написать код к стартовой матрице задачи l , который воспроизводит вывод, показанный ниже

In [45]:
print(mat[3:])

[[16 17 18 19 20]
 [21 22 23 24 25]]


Получить сумму всех значений в стартовой матрице mat

In [49]:
print(mat.sum())

325


Получить стандартное отклонение в стартовой матрице mat

In [51]:
print(np.std(mat))

7.211102550927978


Получить сумму значений в колонках в стартовой матрице mat

In [50]:
print(mat.sum(axis=0))

[55 60 65 70 75]
